FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git unzip sqlite3 libsqlite3-dev libzip-dev \
    && docker-php-ext-install pdo pdo_sqlite zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

RUN chown -R www-data:www-data /var/www \
    && chmod -R 755 storage bootstrap/cache \
    && chmod -R 755 public

RUN composer install --no-dev --optimize-autoloader

RUN cp .env.example .env || true \
    && php artisan key:generate || true

EXPOSE 9000

CMD sh -c "composer install && \
           chmod -R 777 storage bootstrap/cache && \
           chmod -R 777 database && \
           touch database/database.sqlite && \
           chmod 666 database/database.sqlite && \
           chmod -R 755 public && \
           mkdir -p storage/app/public && \
           rm -f public/storage && \
           php artisan storage:link && \
           chmod -R 777 public/storage storage/app/public && \
           php artisan migrate --force && \
           (php artisan db:seed --force || true) && \
           php-fpm"